#!/bin/sh

DOCKCMD="docker"
# Prefer podman if installed
if [ -x "$(command -v podman)" ]; then
	DOCKCMD="podman"
fi

CIDFILE=qemu-static.cid
if [ -f "${CIDFILE}" ]; then
	rm -f "${CIDFILE}"
fi

# 1. Build container
echo "Building container..."
"${DOCKCMD}" build --no-cache --tag qemu-static . || exit 1

# 2. Run container to copy artifacts from
echo "Running container..."
"${DOCKCMD}" run -it --cidfile="${CIDFILE}" qemu-static true

# 3. Copy artifacts
echo "Copying artifacts from container..."
"${DOCKCMD}" cp "$(cat "${CIDFILE}"):artifact/." artifact || exit 1


